const assetList = {
    "register": {
        "images": [
            "./images/registration/bg-extended.png",
            "./svgs/registration/reg-banner.svg",
            "./svgs/registration/bg-mobile.svg",
            "./svgs/registration/leftarr.svg",
            "./svgs/registration/rightarr.svg",
            "./svgs/registration/dropdown.svg",
            "./svgs/registration/scrollThumb.svg",
            "./svgs/registration/scroll-bar.svg",
            './svgs/registration/back.svg',
            "./images/registration/information.png",
            "./images/registration/info3.png",
        ],
        "videos": []
    },
    "contact": {
        "images": [
            './images/contact/Aryan.png',
            // './images/contact/ContactCard2.png',
            // './images/contact/ContactCard3.png',
            './images/contact/contact-banner.png',
            './images/contact/Ahan.png',
            './images/contact/Arshita.png',
            './images/contact/Ayushmaan.png',
            './images/contact/Dhruv.png',
            // './images/contact/Door1.png',
            // './images/contact/Door2.png',
            './images/contact/Ishita.png',
            './images/contact/Pranav.png',
            './images/contact/Rahul.png',
            './images/contact/ContactCard1.png',
            './images/contact/DoorsCombined.png',
            './images/contact/DoorsMobile.png',
        ],
        "videos": []
    },
    "aboutus": {
        "images": [
            './svgs/aboutus/lines.svg',
            './svgs/aboutus/tree.svg',
            './svgs/aboutus/abt.svg',
            // './svgs/aboutus/dagger.svg',
            // './svgs/aboutus/fan.svg',
            './svgs/aboutus/header.svg',
            // './svgs/aboutus/lantern.svg',
            './svgs/aboutus/letter1.svg',
            './svgs/aboutus/letter2.svg',
            './svgs/aboutus/letter3.svg',
            // './svgs/aboutus/text-frame.svg',
            // './svgs/aboutus/Mask2.svg',
            './svgs/aboutus/bord.svg',
            './svgs/aboutus/fan.png',
            './svgs/aboutus/letter4.svg',
            './svgs/aboutus/letter5.svg',
            './svgs/aboutus/letter6.svg',
            './svgs/aboutus/letter7.svg',
            './svgs/aboutus/letter8.svg',
            './svgs/aboutus/next.svg',
            './svgs/aboutus/pause.svg',
            './svgs/aboutus/prev.svg',
            './images/aboutus/background.jpg',
            './images/aboutus/backg.png',
            './svgs/aboutus/nextarr.svg',
            './svgs/aboutus/play.svg',
            './svgs/aboutus/prvarr.svg',
            './svgs/aboutus/reghead.svg',
            './svgs/aboutus/borde.svg',
            './images/aboutus/abtbck.png',
        ],
        "videos": []
    },
    
}

export default assetList;